### PR TITLE
Tariff and other fixes for os32

### PR DESCRIPTION
**Pull request by DavidGoldwasser**
Should be ready for next release of gem after this is merged in

### CODE REVIEW

**Review by nllong — COMMENTED** [review]
looks great! Thanks! 

Are we okay pinning to a release candidate for OS standards?

**Comment by nllong** [comment]
> looks great! Thanks!
> 
> Are we okay pinning to a release candidate for OS standards?

@DavidGoldwasser -- I wanted to make sure that we are okay pinning to a RC? That seems concerning to be honest since standards is foundational to everything we do. Should this then also be an RC?

**Comment by DavidGoldwasser** [comment]
@nllong just as an update a non-rc version of standards gem is being worked on, and I'm also updating extension gem to 0.4.2 (adding in ASHRAE 90.1 2016 and 2019). Once standards is released, then I can merge 0.4.2 extension gem. Once that is released then I can setup and merge this and other measure gems.

**Comment by DavidGoldwasser** [comment]
@nllong second measure gem repo ready for release.

**Review by nllong — APPROVED** [review]
suweet 🤜🤛

**Pull request merged**
