### PR TITLE
move errs array creation to in case model run is skipped

### PR DESCRIPTION
**Pull request by mdahlhausen**

### CODE REVIEW

**Comment by nllong** [comment]
@mdahlhausen -- is this something we want to get into 3.1.0?

**Comment by mdahlhausen** [comment]
@nllong yes, the measure will often fail without this change

**Comment by nllong** [comment]
okay. Can you resolve the conflict @mdahlhausen?

**Comment by mdahlhausen** [comment]
per @DavidGoldwasser, this measure has been moved to the model articulation gem repo

**Pull request closed without merging**
