### PR TITLE
prepping 0.6.1 release

### PR DESCRIPTION
**Pull request by kflemin**

### CODE REVIEW

**Review by nllong — APPROVED** [review]
🔥🥳

**Comment by nllong** [comment]
let me know when you want this released? Now?

**Comment by nllong** [comment]
nvm, need to wait until [this](https://github.com/NREL/openstudio-common-measures-gem/pull/108) is merged.

**Comment by kflemin** [comment]
nllong, i'm not sure we are merging that other PR...I think Rawad had to do a workaround @rawadelkontar ?

**Comment by kflemin** [comment]
@nllong confirmed with Rawad that we do not want to merge PR#108 for this release.  You can release now!

**Comment by nllong** [comment]
sweet, i'll release in a bit.

**Comment by nllong** [comment]
dunzo... https://github.com/NREL/openstudio-common-measures-gem/releases/tag/v0.6.1

**Comment by kflemin** [comment]
🏆🔥

**Pull request merged**
