### PR TITLE
add customization for revit to openstudio results

### PR DESCRIPTION
**Pull request by MatthewSteen**
Adds a small customization to the OpenStudio Results measure for Revit's Systems Analysis workflow from https://github.com/NREL/gbxml-to-openstudio/measures to reduce redundancy and establish a single source of truth. When/if this is merged, the duplicate OpenStudio Results measure can be removed from the gbxml-to-openstudio repo.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
@MatthewSteen I like the idea of having single measure. The new `revit` argument does two things. Instead of having an argument to set unit it gets it from the OSW, it also adds the E+ eplustbl.

I propose a small modification to make these changes more generally applicable for other use cases. 

1. We already have a `units` choice argument that has `IP` and `SI` as choices. We can add a third  option here that says `Get Units from OSW File`.
2. the `revit` argument can be renamed `Add EnergyPlus Detailed Report`. It looks like the current revit argument is also turning the measure warnings section, but there is already a bool argument for that to be turned off.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser I'll work on adding a test for the new units choice, which is an `OSRunner` [method](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.6.0-doc/measure/html/classopenstudio_1_1measure_1_1_o_s_runner.html) that's not associated with the `WorkflowJSON (OSW)` class/object.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen ahh assumed maybe it was in the OSW and then loaded here
https://github.com/NREL/openstudio-common-measures-gem/blob/update/openstudio-results-for-revit/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb#L162

Or is the only way to populate the units with another runner method.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen I didn't get to this last night, but I can review this afternoon.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser I'm not ready for another review yet. I need to test the measure with the Revit Systems Analysis workflow before it's ready again. After I've done that I'll change this to `ready for review` again.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser one of the customizations is in the [report.html.erb](https://github.com/NREL/gbxml-to-openstudio/blob/193e50dfaa4f55ac9d9670a3821c374e88f04d0e/measures/openstudio_results/resources/report.html.erb#L54-L57) file, which replaces the *distributed* javascript library sources with *local* copies in the `/resources` folder. 

If this is ok with you, I'll commit those files and add code to replace the sources.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen Yes, I'm fine with change to use local javascript files

**Comment by MatthewSteen** [comment]
@DavidGoldwasser this is ready for a review.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser this is ready for review.

**Review by DavidGoldwasser — APPROVED** [review]

**Comment by MatthewSteen** [comment]
@DavidGoldwasser I need to do some more testing to confirm that this works with the Autodesk workflow.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser this is ready.

**Comment by DavidGoldwasser** [comment]
Failing at few different areas:

```
Failure: test_edge_model(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:338:in `test_edge_model'
--
Error | Failure: test_empty_model(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:431:in `test_empty_model'
Error | Failure: test_heating_only(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:721:in `test_heating_only'
Error | Failure: test_period_in_const_name(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:648:in `test_period_in_const_name'
Error | Failure: test_sm_hotel(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:575:in `test_sm_hotel'
Error | Failure: test_tariff(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:824:in `test_tariff'
Error | Failure: test_example_model(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:179:in `test_example_model'
Error | Failure: test_example_model_si(Minitest::Result) [/srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326]: RuntimeError: Optional not initialized /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `get' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/measure.rb:326:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-134/21/lib/measures/openstudio_results/tests/OpenStudioResults_Test.rb:251:in `test_example_model_si'
```

**Pull request merged**
