### PR TITLE
fix filenames and ignore staged dir

### PR DESCRIPTION
**Pull request by kflemin**

### CODE REVIEW

**Review by DavidGoldwasser — APPROVED** [review]

**Comment by DavidGoldwasser** [comment]
@nllong or @tijcolem any ideas what this CI failure means, `hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: linux_base for class: openstudio_extension_gems`

**Comment by nllong** [comment]
That is ne wto me.

**Comment by tijcolem** [comment]
Looks like an error related to moving tp on-prem build agents. I have a fix in and re-running this now.

**Comment by nllong** [comment]
cool, thanks @tijcolem

**Pull request merged**
