### PR TITLE
Bonnema/add

### PR DESCRIPTION
**Pull request by bonnema**

### CODE REVIEW

**Comment by nllong** [comment]
@DavidGoldwasser -- Jenkins is showing that 2.8.1 failed... is that as expected? I'm not concerned that 3.0 has failed. Still merge?

**Comment by DavidGoldwasser** [comment]
@nllong yes, 2.8.1 will fail, this is designed to work with 2.9.1

**Comment by nllong** [comment]
Using #47 instead of this PR.

**Comment by nllong** [comment]
wrong PR... sorry

**Pull request merged**
