### PR TITLE
add measure for SimulationControl

### PR DESCRIPTION
**Pull request by MatthewSteen**
Add a measure for the `SimulationControl` class, which was originally written in https://github.com/NREL/gbxml-to-openstudio/tree/193e50dfaa4f55ac9d9670a3821c374e88f04d0e/measures/set_simulation_control.

### CODE REVIEW

**Comment by DavidGoldwasser** [comment]
If we are going to add this need at least a test.rb file and a measure.xml

**Comment by DavidGoldwasser** [comment]
@MatthewSteen If Autodesk is going to use that and we needed in installer we can try to get this added in the next day or two

**Comment by MatthewSteen** [comment]
No, this is a longer term effort, thanks.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser this is ready for a review.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser this is ready for review.

**Pull request merged**
