### PR TITLE
adding XcelEDAReportingandQAQC measure

### PR DESCRIPTION
**Pull request by tijcolem**
Moving a measure from OpenStudio-measures to here to make it public and accessible on BCL. 

See related pr https://github.com/NREL/OpenStudio-measures/pull/337

### CODE REVIEW

**Comment by kflemin** [comment]
@tijcolem, I think there are other Xcel measures in use...should we move them too?  I'm thinking specifically of XcelEDATariffSelectionandModelSetup

**Comment by tijcolem** [comment]
@kflemin Yep, this would be a good time move the ones that are actively being used.  I can moved that one over.

**Comment by tijcolem** [comment]
@kflemin it's added. let me know if there are others.

**Comment by tijcolem** [comment]
I need to find out why this failing. It looks like it's using another measure that might also need to be updated.

**Comment by tijcolem** [comment]
@kflemin It's failing due to a dependent measure - generic_qaqc - that makes use of a deprecated emum fuel type value in OpenStudio.  I'll see if I can fix.

**Comment by tijcolem** [comment]
@kflemin I added a GH Actions to this PR and provided those pass, we can merge. I'll disable Jenkins once I have the entire pipeline moved over (the html static result files that get pushed to S3 needs to be added).

**Comment by tijcolem** [comment]
@kflemin Tests are passing on GitHub Actions so I we can merge. We can dig into Jenkins if we want to, but if we are going to move over GitHub Actions probably not worth it.

**Review by kflemin — APPROVED** [review]

**Pull request merged**
